esphome:
  name: century-vs-pump-controller
  on_boot:
    then:
      - light.turn_on:
          id: status_led
          blue: 1.0
          brightness: 0.3
          green: 1.0
          red: 1.0

esp32:
  board: m5stack-atom
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: century-vs-pump-controller
    password: !secret ap_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

external_components:
  - source:
      type: git
      url: https://github.com/Ixian/ESPHome_VSPump
      ref: additional_features

uart:
  id: mod_uart
  baud_rate: 9600
  tx_pin: GPIO26
  rx_pin: GPIO32
  debug:
    direction: BOTH
    dummy_receiver: false

modbus:
  id: mod_bus
  uart_id: mod_uart

centuryvspump:
  id: pool_pump
  address: 21
  modbus_id: mod_bus
  update_interval: 10s

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: Pool Pump Controller LED
    pin: GPIO27
    num_leds: 1
    chipset: SK6812
    rgb_order: GRB

binary_sensor:
  - platform: gpio
    name: Pool Pump Controller Button
    pin:
      number: GPIO39
      inverted: true

switch:
  - platform: centuryvspump
    name: Pool Pump Controller Run
    id: pump_run

number:
  - platform: centuryvspump
    name: Pool Pump Controller Demand
    id: pump_speed
    unit_of_measurement: RPM

  - platform: centuryvspump
    name: Pool Pump Serial Timeout
    id: serial_timeout
    type: serial_timeout
    store_to_flash: true
    unit_of_measurement: s

  # Freeze protection settings
  - platform: centuryvspump
    name: Pool Pump Freeze Protection Enabled
    id: freeze_enable
    type: freeze_enable
    store_to_flash: true

  - platform: centuryvspump
    name: Pool Pump Freeze Temp Threshold
    id: freeze_temp
    type: freeze_temp
    store_to_flash: true
    unit_of_measurement: "°F"

  - platform: centuryvspump
    name: Pool Pump Freeze Protection Speed
    id: freeze_speed
    type: freeze_speed
    store_to_flash: true
    unit_of_measurement: RPM

  # Priming settings
  - platform: centuryvspump
    name: Pool Pump Priming Duration
    id: priming_duration
    type: priming_duration
    store_to_flash: true
    unit_of_measurement: min

  - platform: centuryvspump
    name: Pool Pump Priming Speed
    id: priming_speed
    type: priming_speed
    store_to_flash: true
    unit_of_measurement: RPM

  # Pause (temporary stop)
  - platform: centuryvspump
    name: Pool Pump Pause Duration
    id: pause_duration
    type: pause_duration
    store_to_flash: true
    unit_of_measurement: min

sensor:
  - platform: centuryvspump
    name: Pool Pump Controller RPM
    type: rpm
    unit_of_measurement: RPM

  - platform: centuryvspump
    name: Pool Pump Controller Demand Readback
    address: 3
    page: 0
    scale: 4
    type: custom
    unit_of_measurement: RPM

  - platform: wifi_signal
    name: Pool Pump Controller Wifi Signal
    update_interval: 60s

button:
  - platform: template
    name: Pool Pump Demand 600RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 600

  - platform: template
    name: Pool Pump Demand 2000RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 2000

  - platform: template
    name: Pool Pump Demand 2600RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 2600

  - platform: template
    name: Pool Pump Demand 3450RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 3450

  - platform: restart
    name: Pool Pump Controller Restart

web_server:
  local: true
  port: 80
