esphome:
  name: century-vs-pump-controller
  friendly_name: Century VS Pump Controller
  on_boot:
    then:
      - light.turn_on:
          id: status_led
          red: 1.0
          green: 1.0
          blue: 1.0
          brightness: 0.3

esp32:
  board: m5stack-atom
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: century-vs-pump-controller
    password: !secret ap_password

captive_portal:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

external_components:
  - source:
      type: git
      url: https://github.com/Ixian/ESPHome_VSPump
      ref: main

uart:
  id: mod_uart
  baud_rate: 9600
  tx_pin: GPIO26
  rx_pin: GPIO32
  debug:
    direction: BOTH
    dummy_receiver: false

modbus:
  id: mod_bus
  uart_id: mod_uart

centuryvspump:
  id: pool_pump
  address: 21
  modbus_id: mod_bus
  update_interval: 10s

light:
  - platform: esp32_rmt_led_strip
    id: status_led
    name: Status LED
    pin: GPIO27
    num_leds: 1
    chipset: SK6812
    rgb_order: GRB

binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO39
      inverted: true

switch:
  - platform: centuryvspump
    name: Pump Run
    id: pump_run

  # Template switch for freeze protection (shows On/Off instead of 1/0)
  - platform: template
    name: Freeze Protection
    id: freeze_protection_switch
    icon: mdi:snowflake-alert
    lambda: 'return id(freeze_enable_num).state == 1;'
    turn_on_action:
      - number.set:
          id: freeze_enable_num
          value: 1
    turn_off_action:
      - number.set:
          id: freeze_enable_num
          value: 0

number:
  # Demand control (default type) - sets pump target speed
  - platform: centuryvspump
    name: Pump Demand
    id: pump_speed
    unit_of_measurement: RPM

  # Configuration registers use page/address from pump documentation
  # type: config = single byte (uint8), type: config16 = two bytes (uint16)
  # offset: added to stored value when reading, subtracted when writing

  # Serial timeout (page 1, address 0x00) - failsafe if controller goes offline
  - platform: centuryvspump
    name: Serial Timeout
    id: serial_timeout
    type: config
    page: 1
    address: 0x00
    min_value: 0
    max_value: 250
    store_to_flash: true
    unit_of_measurement: s

  # Freeze protection settings (page 10)
  # Hidden - controlled by template switch above
  - platform: centuryvspump
    name: Freeze Enable Raw
    id: freeze_enable_num
    type: config
    page: 10
    address: 0x06
    min_value: 0
    max_value: 1
    store_to_flash: true
    entity_category: diagnostic
    internal: true

  - platform: centuryvspump
    name: Freeze Temp Threshold
    id: freeze_temp
    type: config
    page: 10
    address: 0x07
    offset: 32  # Pump stores 0-18, display as 32-50 F
    min_value: 32
    max_value: 50
    store_to_flash: true
    unit_of_measurement: "F"

  - platform: centuryvspump
    name: Freeze Protection Speed
    id: freeze_speed
    type: config16
    page: 10
    address: 0x09
    min_value: 600
    max_value: 3450
    step: 50
    store_to_flash: true
    unit_of_measurement: RPM

  # Priming settings (page 10)
  - platform: centuryvspump
    name: Priming Duration
    id: priming_duration
    type: config
    page: 10
    address: 0x02
    min_value: 0
    max_value: 30
    store_to_flash: true
    unit_of_measurement: min

  - platform: centuryvspump
    name: Priming Speed
    id: priming_speed
    type: config16
    page: 10
    address: 0x03
    min_value: 600
    max_value: 3450
    step: 50
    store_to_flash: true
    unit_of_measurement: RPM

  # Pause (temporary stop) - page 10
  - platform: centuryvspump
    name: Pause Duration
    id: pause_duration
    type: config
    page: 10
    address: 0x0B
    min_value: 0
    max_value: 30
    store_to_flash: true
    unit_of_measurement: min

sensor:
  # Current motor RPM
  - platform: centuryvspump
    name: Pump RPM
    type: rpm
    unit_of_measurement: RPM

  # Demand readback from pump
  - platform: centuryvspump
    name: Demand Readback
    address: 3
    page: 0
    scale: 4
    type: custom
    unit_of_measurement: RPM

  # Temperature sensors
  - platform: centuryvspump
    name: Ambient Temperature
    address: 7
    page: 0
    scale: 128
    type: custom
    unit_of_measurement: "F"
    filters:
      - offset: 32

  - platform: centuryvspump
    name: IGBT Temperature
    address: 18
    page: 0
    scale: 128
    type: custom
    unit_of_measurement: "F"
    filters:
      - offset: 32

  # Raw status values (hidden - used by template text_sensors)
  - platform: centuryvspump
    name: Motor Status Raw
    id: motor_status_raw
    address: 8
    page: 0
    scale: 1
    type: custom
    internal: true

  - platform: centuryvspump
    name: Prime Status Raw
    id: prime_status_raw
    address: 16
    page: 0
    scale: 1
    type: custom
    internal: true

  - platform: centuryvspump
    name: Previous Fault Raw
    id: previous_fault_raw
    address: 9
    page: 0
    scale: 1
    type: custom
    internal: true

  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s

text_sensor:
  # Human-readable status from raw sensor values
  - platform: template
    name: Motor Status
    id: motor_status
    lambda: |-
      int raw = (int)id(motor_status_raw).state;
      switch (raw) {
        case 0x00: return {"Stopped"};
        case 0x09: return {"Starting"};
        case 0x0B: return {"Running"};
        case 0x20: return {"Fault"};
        default: return {"Unknown"};
      }
    update_interval: 10s

  - platform: template
    name: Prime Status
    id: prime_status
    lambda: |-
      int raw = (int)id(prime_status_raw).state;
      switch (raw) {
        case 0: return {"Idle"};
        case 1: return {"Priming"};
        case 2: return {"Complete"};
        default: return {"Unknown"};
      }
    update_interval: 10s

  - platform: template
    name: Previous Fault
    id: previous_fault
    lambda: |-
      int raw = (int)id(previous_fault_raw).state;
      switch (raw) {
        case 0x00: return {"None"};
        case 0x21: return {"Overcurrent"};
        case 0x22: return {"DC Overvoltage"};
        case 0x2E: return {"IGBT Overtemp"};
        case 0x3E: return {"Comm Loss"};
        case 0x3F: return {"Generic Fault"};
        case 0x40: return {"Coherence Fault"};
        case 0x41: return {"UL Fault"};
        default:
          char buf[16];
          snprintf(buf, sizeof(buf), "Code 0x%02X", raw);
          return {buf};
      }
    update_interval: 10s

button:
  - platform: template
    name: Set 600 RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 600

  - platform: template
    name: Set 2000 RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 2000

  - platform: template
    name: Set 2600 RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 2600

  - platform: template
    name: Set 3450 RPM
    on_press:
      then:
        - number.set:
            id: pump_speed
            value: 3450

  - platform: restart
    name: Restart

web_server:
  local: true
  port: 80
